functions:
- input:
    keys:
      from: GLOBAL
      type: str
    payload_size:
      from: GLOBAL
      type: int
  name: f1
  next:
    nodes:
    - f2
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f1
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2
  next:
    type: FINISH
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2
