STORAGE_NODE_IP = '10.3.96.150'

COUCHDB_URL = f'http://faasnap:faasnap@{STORAGE_NODE_IP}:5984'
DATADB_URL = ""
CACHE_HOST = '172.17.0.1' 
REDIS_PORT = 6379
REDIS_CACHE_PORT = 6380
REDIS_SHADOW_TABLE_DB = 0
REDIS_CACHE_DB = 1
DYNAMODB_URL = f'http://{STORAGE_NODE_IP}:4567'
DYNAMODB_KEY_ID = 'FAASNAPDYNAMODB'
DYNAMODB_ACCESS_KEY = 'FAASNAPDYNAMODBKEY'
DYNAMODB_AREA = 'us-west-2'

GATEWAY_ADDR = f'{STORAGE_NODE_IP}:8000'

RUNNING = '1'
REPAIRED = '2'
ABORTED = '3'

OPT_REPAIR = 1
PESSI_REPAIR = 2

