STORAGE_NODE_IP = '10.2.29.142'

COUCHDB_URL = f'http://faasnap:faasnap@{STORAGE_NODE_IP}:5984'
DATADB_URL = ""
CACHE_HOST = '172.17.0.1' 
REDIS_PORT = 6379
REDIS_CACHE_PORT = 6380
REDIS_SHADOW_TABLE_DB = 0
REDIS_CACHE_DB = 1
DYNAMODB_URL = f'http://{STORAGE_NODE_IP}:4567'
DYNAMODB_KEY_ID = 'FAASNAPDYNAMODB'
DYNAMODB_ACCESS_KEY = 'FAASNAPDYNAMODBKEY'
DYNAMODB_AREA = 'us-west-2'
GATEWAY_ADDR = f'{STORAGE_NODE_IP}:8000'
SYSTEM_MODE = __import__('os').environ.get('SYSTEM_MODE', 'BOKI_SN').upper()
LOCK_MANAGER_ADDR = __import__('os').environ.get('LOCK_MANAGER_ADDR', f'{STORAGE_NODE_IP}:9000')
SHADOW_SERVICE_ADDR = __import__('os').environ.get('SHADOW_SERVICE_ADDR', f'{STORAGE_NODE_IP}:9100')
LOCK_WAIT_DEADLINE_SECONDS = float(__import__('os').environ.get('LOCK_WAIT_DEADLINE_SECONDS', '30'))

