functions:
  - name: social_login
    source: social_login
    input: 
        user_id:
            from: GLOBAL
            type: str
        password:
            from: GLOBAL
            type: str
        comment_post_id:
            from: GLOBAL
            type: str
        transaction_id:
            from: GLOBAL
            type: str
    output:
        user_id:
            type: str
        comment_post_id:
            type: str
        transaction_id:
            type: str
    next: 
        type: pass
        nodes:
            - check_mailbox
            - publish
  - name: check_mailbox
    source: check_mailbox
    input: 
        user_id:
            from: social_login
            type: str
    output:
        new_post_ids:
            type: str
    next: 
        type: pass
        nodes:
            - send_comment
  - name: send_comment
    source: send_comment
    input: 
       user_id:
            from: social_login
            type: str
       new_post_ids:
           from: check_mailbox
           type: str
       comment_post_id:
           from: social_login
           type: str
    output:
        comment_num:
            type: int
    next: 
        type: pass
        nodes:
            - modify_timeline
  - name: publish
    source: publish
    input:
        user_id:
            from: social_login
            type: str
        transaction_id:
            from: social_login
            type: str
    output:
        publish_post_id:
            type: str
    next:
        type: pass
        nodes:
            - notify_follower
  - name: notify_follower
    source: notify_follower
    input:
        user_id:
            from: social_login
            type: str
        publish_post_id:
            from: publish
            type: str
    output:
        notify_num:
            type: int
    next:
        type: pass
        nodes:
            - modify_timeline
  - name: modify_timeline
    source: modify_timeline
    input: 
        user_id:
            from: social_login
            type: str
        publish_post_id:
            from: publish
            type: str
        comment_num:
            from: send_comment
            type: int
        notify_followers_num:
            from: notify_follower
            type: int
    output:
        timeline_length:
            type: int
        publish_post_id:
            type: str
        comment_num:
            type: int
        notify_followers_num:
            type: int
    next: 
        type: FINISH