functions:
- input:
    keys:
      from: GLOBAL
      type: str
    payload_size:
      from: GLOBAL
      type: int
    retry_abort_func:
      from: GLOBAL
      type: str
  name: f1
  next:
    nodes:
    - f2
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
    retry_abort_func:
      type: str
  source: f1
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
    retry_abort_func:
      from: f1
      type: str
  name: f2
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
    retry_abort_func:
      type: str
  source: f2
- input:
    keys:
      from: f2
      type: str
    payload_size:
      from: f2
      type: int
    retry_abort_func:
      from: f2
      type: str
  name: f3
  next:
    nodes:
    - f4
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
    retry_abort_func:
      type: str
  source: f3
- input:
    keys:
      from: f3
      type: str
    payload_size:
      from: f3
      type: int
    retry_abort_func:
      from: f3
      type: str
  name: f4
  next:
    type: FINISH
  output:
    keys:
      type: str
    payload_size:
      type: int
    retry_abort_func:
      type: str
  source: f4
