functions:
  - name: f1
    source: f1
    input: 
        t0:
            from: GLOBAL
            type: str
    output:
        t3:
            type: str
    next: 
        type: pass
        nodes:
            - f2
  - name: f2
    source: f2
    input: 
        t3:
            from: f1
            type: str
    output:
        t5:
            type: str
    next: 
        type: pass
        nodes:
            - f3
  - name: f3
    source: f3
    input: 
        t5:
            from: f2
            type: str
    output:
        t7:
            type: str
    next: 
        type: pass
        nodes:
            - f4
  - name: f4
    source: f4
    input: 
        t7:
            from: f3
            type: str
    output:
        t9:
            type: str
    next: 
        type: pass
        nodes:
            - f5
  - name: f5
    source: f5
    input: 
        t9:
            from: f4
            type: str
    output:
        t11:
            type: str
    next: 
        type: FINISH