functions:
  - name: func1
    source: func1
    next: 
        type: pass
        nodes:
            - func2
  - name: func2
    source: func2
    next: 
        type: pass
        nodes:
            - func3
  - name: func3
    source: func3
    next: 
        type: pass
        nodes:
            - func4
  - name: func4
    source: func4
    next: 
        type: FINISH
