functions:
- input:
    keys:
      from: GLOBAL
      type: str
    payload_size:
      from: GLOBAL
      type: int
  name: f1
  next:
    nodes:
    - f2_1
    - f2_2
    - f2_3
    - f2_4
    - f2_5
    - f2_6
    - f2_7
    - f2_8
    - f2_9
    - f2_10
    - f2_11
    - f2_12
    - f2_13
    - f2_14
    - f2_15
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f1
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_1
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_1
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_2
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_2
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_3
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_3
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_4
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_4
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_5
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_5
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_6
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_6
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_7
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_7
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_8
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_8
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_9
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_9
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_10
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_10
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_11
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_11
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_12
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_12
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_13
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_13
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_14
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_14
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f2_15
  next:
    nodes:
    - f3
    type: pass
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f2_15
- input:
    keys:
      from: f1
      type: str
    payload_size:
      from: f1
      type: int
  name: f3
  next:
    type: FINISH
  output:
    keys:
      type: str
    payload_size:
      type: int
  source: f3
